---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtools-api-gateway
spec:
  selector:
    matchLabels:
      app: webtools-api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: webtools-api-gateway
    spec:
      containers:
      - name: webtools-api-gateway
        image: "ikoyski/webtools-api-gateway:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 8190
---
apiVersion: v1
kind: Service
metadata:
  name: webtools-api-gateway
spec:
  selector:
    app: webtools-api-gateway
  ports:
  - protocol: "TCP"
    port: 8190
    targetPort: 8190
  type: NodePort
  